
name: Playwright CI/CD with GA
on:
  push:
    branches:
    - '**'
jobs:
  Playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: Install Playwright Test package
        run: npm i -D @playwright/test
      - name: install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: npx playwright test
      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Playwrighht-Report
      #     path: /Playwright-CI-CD/pw/Playwrighht-Report
